-- Authentic daemon SQLite dump produced by spl commit
-- c1d7c72719fd06411f74a3b25b9b7423f4c9f780 (Release 0.1.4).
-- Generated by that revision's RegistryStore/register/create_run/update_run
-- APIs; do not regenerate from the current schema.
BEGIN TRANSACTION;
CREATE TABLE environment_builds (
                    spec_hash TEXT PRIMARY KEY,
                    base_python TEXT NOT NULL,
                    python_version TEXT NOT NULL,
                    distributions_json TEXT NOT NULL,
                    runtime_packages_json TEXT NOT NULL,
                    spec_json TEXT NOT NULL,
                    venv_path TEXT NOT NULL,
                    python_path TEXT NOT NULL,
                    status TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    started_at TEXT,
                    finished_at TEXT,
                    error TEXT,
                    install_log_path TEXT,
                    runtime_type TEXT NOT NULL DEFAULT 'venv',
                    image_tag TEXT,
                    base_image TEXT
                );
CREATE TABLE envs (
                    name TEXT PRIMARY KEY,
                    python TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );
INSERT INTO "envs" VALUES('default','/usr/bin/python3','2026-07-15T02:09:17.572459+00:00','2026-07-15T02:09:17.572459+00:00');
CREATE TABLE object_functions (
                    id TEXT PRIMARY KEY,
                    object_id TEXT NOT NULL,
                    object_version_id TEXT NOT NULL,
                    role TEXT NOT NULL,
                    node_id TEXT,
                    name TEXT NOT NULL,
                    inputs_json TEXT NOT NULL,
                    outputs_json TEXT NOT NULL,
                    metadata_json TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    FOREIGN KEY(object_id) REFERENCES objects(id),
                    FOREIGN KEY(object_version_id) REFERENCES object_versions(id)
                );
INSERT INTO "object_functions" VALUES('a6ceda804fd745e88d8d3ce37c7932ac','a5c533c28bdf46f3b86187628a168cb6','a4b897f14c35465289699b1c14e57cd8','top_level',NULL,'demo_obj','[]','[{"name": "default", "type": "int"}]','{"distributions": [], "entrypoint": "demo_obj", "imports": [], "inputs": [], "internal_objects": [{"inputs": [], "kind": "function", "name": "demo_obj", "outputs": [{"name": "default", "type": "int"}]}], "kind": "function", "outputs": [{"name": "default", "type": "int"}], "pipeline_nodes": []}','2026-07-15T02:09:17.573164+00:00');
CREATE TABLE object_pipeline_links (
                    id TEXT PRIMARY KEY,
                    object_id TEXT NOT NULL,
                    object_version_id TEXT NOT NULL,
                    target_node_id TEXT NOT NULL,
                    target_port TEXT NOT NULL,
                    source_kind TEXT NOT NULL,
                    source_node_id TEXT,
                    source_port TEXT,
                    scalar_json TEXT,
                    link_json TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    FOREIGN KEY(object_id) REFERENCES objects(id),
                    FOREIGN KEY(object_version_id) REFERENCES object_versions(id)
                );
CREATE TABLE object_pipeline_nodes (
                    id TEXT PRIMARY KEY,
                    object_id TEXT NOT NULL,
                    object_version_id TEXT NOT NULL,
                    node_id TEXT NOT NULL,
                    node_kind TEXT NOT NULL,
                    name TEXT NOT NULL,
                    function_name TEXT,
                    remote_json TEXT NOT NULL,
                    inputs_json TEXT NOT NULL,
                    outputs_json TEXT NOT NULL,
                    metadata_json TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    FOREIGN KEY(object_id) REFERENCES objects(id),
                    FOREIGN KEY(object_version_id) REFERENCES object_versions(id),
                    UNIQUE(object_version_id, node_id)
                );
CREATE TABLE object_versions (
                    id TEXT PRIMARY KEY,
                    object_id TEXT NOT NULL,
                    version INTEGER NOT NULL,
                    version_label TEXT,
                    description TEXT NOT NULL DEFAULT '',
                    entrypoint TEXT NOT NULL,
                    env TEXT NOT NULL,
                    env_python TEXT NOT NULL,
                    kind TEXT NOT NULL,
                    yaml_text TEXT NOT NULL,
                    yaml_sha256 TEXT NOT NULL,
                    content_hash TEXT,
                    metadata_json TEXT NOT NULL,
                    inputs_json TEXT NOT NULL,
                    outputs_json TEXT NOT NULL,
                    pipeline_nodes_json TEXT NOT NULL,
                    distributions_json TEXT NOT NULL,
                    runtime_config_json TEXT NOT NULL DEFAULT '{"mode":"venv"}',
                    workdir TEXT,
                    remote_owner_id TEXT,
                    remote_object_id TEXT,
                    remote_version_id TEXT,
                    created_at TEXT NOT NULL,
                    FOREIGN KEY(object_id) REFERENCES objects(id),
                    FOREIGN KEY(env) REFERENCES envs(name),
                    UNIQUE(object_id, version),
                    UNIQUE(object_id, content_hash)
                );
INSERT INTO "object_versions" VALUES('a4b897f14c35465289699b1c14e57cd8','a5c533c28bdf46f3b86187628a168cb6',1,NULL,'','demo_obj','default','/usr/bin/python3','function','- !DFunction
  name: demo_obj
  inputs: []
  outputs:
  - name: default
    type: int
  body: |-
    return 1
','bf3127488e9fcb4075f5c5283ed1080d7bd062d96cbde2f7eb1e227a33a4cd8d','0c7c644eded9bdcdeff3afa2360551c944a88753cc0fd14d0478c8198b158b9e','{"distributions": [], "entrypoint": "demo_obj", "imports": [], "inputs": [], "internal_objects": [{"inputs": [], "kind": "function", "name": "demo_obj", "outputs": [{"name": "default", "type": "int"}]}], "kind": "function", "outputs": [{"name": "default", "type": "int"}], "pipeline_nodes": []}','[]','[{"name": "default", "type": "int"}]','[]','[]','{"mode": "venv"}',NULL,NULL,NULL,NULL,'2026-07-15T02:09:17.573164+00:00');
CREATE TABLE objects (
                    id TEXT PRIMARY KEY,
                    owner_id TEXT NOT NULL,
                    library TEXT NOT NULL DEFAULT 'default',
                    name TEXT NOT NULL,
                    kind TEXT,
                    origin TEXT NOT NULL DEFAULT 'local',
                    remote_owner_id TEXT,
                    remote_object_id TEXT,
                    source_object_name TEXT,
                    remote_name TEXT GENERATED ALWAYS AS (source_object_name) VIRTUAL,
                    description TEXT NOT NULL DEFAULT '',
                    current_version_id TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    UNIQUE(owner_id, library, name)
                );
INSERT INTO "objects" VALUES('a5c533c28bdf46f3b86187628a168cb6','local','default','demo_obj','function','local',NULL,NULL,NULL,'','a4b897f14c35465289699b1c14e57cd8','2026-07-15T02:09:17.573164+00:00','2026-07-15T02:09:17.573164+00:00');
CREATE TABLE remote_signatures (
                    id TEXT PRIMARY KEY,
                    server_url TEXT NOT NULL,
                    owner_id TEXT,
                    library TEXT,
                    object_name TEXT NOT NULL,
                    version TEXT,
                    version_id TEXT,
                    signature_json TEXT NOT NULL,
                    status TEXT NOT NULL,
                    error TEXT,
                    fetched_at TEXT,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL
                );
CREATE TABLE runs (
                    id TEXT PRIMARY KEY,
                    object_id TEXT NOT NULL,
                    object_version_id TEXT NOT NULL,
                    object_name TEXT NOT NULL,
                    object_version INTEGER NOT NULL,
                    entrypoint TEXT NOT NULL,
                    env TEXT NOT NULL,
                    env_python TEXT NOT NULL,
                    status TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    started_at TEXT,
                    finished_at TEXT,
                    run_dir TEXT NOT NULL,
                    input_json TEXT NOT NULL,
                    result_path TEXT NOT NULL,
                    result_json TEXT,
                    artifacts_dir TEXT NOT NULL,
                    env_build_hash TEXT,
                    runtime_config_json TEXT NOT NULL DEFAULT '{"mode":"venv"}',
                    runtime_build_hash TEXT,
                    resolved_runtime TEXT,
                    runtime_backend TEXT,
                    image_tag TEXT,
                    container_id TEXT,
                    resolved_python TEXT,
                    error TEXT,
                    returncode INTEGER,
                    command_json TEXT,
                    stdout_path TEXT,
                    stderr_path TEXT,
                    stdout_text TEXT,
                    stderr_text TEXT,
                    FOREIGN KEY(object_id) REFERENCES objects(id),
                    FOREIGN KEY(object_version_id) REFERENCES object_versions(id)
                );
INSERT INTO "runs" VALUES('d949b8934f954ecdb775fc4741ca2200','a5c533c28bdf46f3b86187628a168cb6','a4b897f14c35465289699b1c14e57cd8','demo_obj',1,'demo_obj','default','/usr/bin/python3','failed','2026-07-15T02:09:17.604958+00:00',NULL,'2026-07-02T18:00:00+00:00','/tmp/spl-c1d7c72-fixture/runs/d949b8934f954ecdb775fc4741ca2200','{"args": [], "kwargs": {"secret": "preserve-me"}, "output": null, "timeout_seconds": null}','/tmp/spl-c1d7c72-fixture/runs/d949b8934f954ecdb775fc4741ca2200/result.json',NULL,'/tmp/spl-c1d7c72-fixture/runs/d949b8934f954ecdb775fc4741ca2200/artifacts','9327308bd34a0788f0cef4972cae61092bd3d28f2e9504dde56388cccfa1d5b6','{"mode": "venv"}',NULL,NULL,NULL,NULL,NULL,NULL,'historical-boom',NULL,NULL,NULL,NULL,NULL,NULL);
CREATE TABLE schema_migrations (
                    id TEXT PRIMARY KEY,
                    applied_at TEXT NOT NULL
                );
INSERT INTO "schema_migrations" VALUES('20260702_object_identity_v1','2026-07-15T02:09:17.572074+00:00');
CREATE TABLE server_connections (
                    id TEXT PRIMARY KEY,
                    server_url TEXT NOT NULL,
                    token_hint TEXT NOT NULL,
                    user_token_hint TEXT,
                    token_secret_ref TEXT,
                    user_token_secret_ref TEXT,
                    token_redacted TEXT NOT NULL,
                    user_token_redacted TEXT,
                    remote_connection_id TEXT,
                    owner_id TEXT,
                    subject_type TEXT,
                    subject_id TEXT,
                    machine_id TEXT NOT NULL,
                    display_name TEXT,
                    capabilities_json TEXT NOT NULL,
                    status TEXT NOT NULL,
                    heartbeat_interval_seconds REAL NOT NULL DEFAULT 60,
                    last_heartbeat_at TEXT,
                    next_heartbeat_at TEXT,
                    lease_expires_at TEXT,
                    last_library_snapshot_hash TEXT,
                    last_library_snapshot_at TEXT,
                    created_at TEXT NOT NULL,
                    connected_at TEXT,
                    disconnected_at TEXT,
                    updated_at TEXT NOT NULL,
                    error TEXT
                );
CREATE TABLE sync_events (
                    id TEXT PRIMARY KEY,
                    kind TEXT NOT NULL,
                    payload_json TEXT NOT NULL,
                    status TEXT NOT NULL,
                    attempts INTEGER NOT NULL DEFAULT 0,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    sent_at TEXT,
                    error TEXT
                );
CREATE INDEX idx_objects_name
                    ON objects(name);
CREATE INDEX idx_object_versions_object
                    ON object_versions(object_id, version);
CREATE INDEX idx_object_functions_version
                    ON object_functions(object_version_id, role, node_id);
CREATE INDEX idx_object_pipeline_nodes_version
                    ON object_pipeline_nodes(object_version_id, node_id);
CREATE INDEX idx_object_pipeline_links_version
                    ON object_pipeline_links(object_version_id, target_node_id, target_port);
CREATE INDEX idx_runs_created
                    ON runs(created_at);
CREATE INDEX idx_environment_builds_status
                    ON environment_builds(status);
CREATE INDEX idx_server_connections_status
                    ON server_connections(status, updated_at);
CREATE INDEX idx_remote_signatures_ref
                    ON remote_signatures(server_url, owner_id, library, object_name, version, version_id);
CREATE UNIQUE INDEX idx_objects_identity
                ON objects(owner_id, library, name)
                ;
CREATE UNIQUE INDEX idx_object_versions_content_hash
                ON object_versions(object_id, content_hash)
                WHERE content_hash IS NOT NULL
                ;
CREATE UNIQUE INDEX idx_objects_remote_object
                ON objects(remote_object_id)
                WHERE remote_object_id IS NOT NULL
                ;
CREATE UNIQUE INDEX idx_object_versions_remote_version
                ON object_versions(remote_version_id)
                WHERE remote_version_id IS NOT NULL
                ;
COMMIT;

