# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys

# Make the package importable for autodoc (works from a checkout without an install).
sys.path.insert(0, os.path.abspath('../../src'))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'splime'
copyright = '2026, Yastrebov Kirill'
author = 'Yastrebov Kirill'
release = '0.2.1'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.apidoc',
]

templates_path = ['_templates']
exclude_patterns = []

language = 'en'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
apidoc_modules = [
    {
        'path': '../../src/spl',
        'destination': 'api',
        # 0.2.0: the implementation lives in private modules (spl._client,
        # spl.core._common); spl.client / spl.core.common are deprecated
        # warning shims scheduled for removal in 0.3.0.  Document the real
        # modules and skip the shims so builds stay warning-free.
        'include_private': True,
        'exclude_patterns': [
            # Literal paths are resolved relative to this conf.py directory;
            # the fnmatch variants are a safety net for absolute-path matching.
            '../../src/spl/client.py',
            '../../src/spl/core/common.py',
            '**/spl/client.py',
            '**/spl/core/common.py',
        ],
    },
]


# -- Autodoc duplicate suppression --------------------------------------------
# ``NodeRemote`` is re-exported through *two* ``__all__`` facades: the
# top-level ``spl`` and ``spl.core``.  For a re-exported class autodoc emits
# ``:canonical: spl.core.entities.node_remote.NodeRemote``, and the Python
# domain registers that canonical name as an alias.  Two alias registrations
# of the same canonical name (api/spl + api/spl.core) trigger "duplicate
# object description ... use :no-index: for one of them", which fails
# ``sphinx-build -W``.  (The real description on the node_remote page never
# conflicts with a single alias: PythonDomain.note_object is silent for
# alias-vs-real in both orders.)
#
# The api/*.rst stubs are regenerated by sphinx.ext.apidoc on every build, so
# the fix has to live here, not in the generated reST.  Policy: NodeRemote is
# documented on its defining page (spl.core.entities.node_remote) and on the
# primary ``spl`` facade page; the secondary ``spl.core`` re-export skips it.
# Deliberately member-targeted: a generic "skip all secondary re-exports"
# rule would silently drop e.g. ``Client`` from the spl.daemon page, where no
# duplicate exists (single alias + real never warns).


def _skip_duplicate_node_remote_reexport(app, what, name, obj, skip, options):
    if skip or what != 'module' or name != 'NodeRemote':
        return None
    # Sphinx 9 (current autodoc) tracks the module being documented on
    # env.current_document; the legacy class-based autodoc used temp_data.
    current_document = getattr(app.env, 'current_document', None)
    modname = getattr(current_document, 'autodoc_module', '') or app.env.temp_data.get(
        'autodoc:module', ''
    )
    if modname == 'spl.core':
        return True  # skip: keep the spl facade + canonical page only
    return None


def setup(app):
    app.connect('autodoc-skip-member', _skip_duplicate_node_remote_reexport)
